### ISSUE TITLE
Wrong decoding with multi-chunk message and `erase_pos` specified

### ISSUE THREAD

**Issue by SupraSummus** [lrq3000/reedsolomon#3]
I get wrong decoding, when decoding multi-chunk message with `erase_pos` specified.

```
>>> import reedsolo
>>> c = reedsolo.RSCodec(nsym=2, nsize=4)
>>> b = c.encode(b'abcd')
>>> b[6] = 0
>>> b[7] = 0
>>> b
bytearray(b'ab\x9c\x9fcd\x00\x00')
>>> c.decode(b, erase_pos=[6, 7])
(bytearray(b'abc\xa5'), bytearray(b'ab\x9c\x9fc\xa5\xc6\x00'))
```

It looks like of-by-one (or 1-based-indexing convention?). When I shift `erase_pos` i get correct result:

```
>>> c.decode(b, erase_pos=[7, 8])
(bytearray(b'abcd'), bytearray(b'ab\x9c\x9fcd\x98\x9f'))
```

I didn't look into the code, but maybe it's related to #1 ?

**Comment by lrq3000** [comment]
This was a bug in chunking that got corrected a long time ago now in other issues, thank you for reporting it first!
