### ISSUE TITLE
TestSimpleFuncs unittest does not run independently

### ISSUE THREAD

**Issue by maqp** [lrq3000/reedsolomon#4]
Running the tests with [xdist](https://docs.pytest.org/en/3.0.0/xdist.html) seems to fail `TestSimpleFuncs.test_rs_simple_encode_msg` occasionally, possibly due to global variables having wrong values. Calling `init_tables()` before `assertEqual` line seems to fix this issue.

**Comment by lrq3000** [comment]
Fixed upstream
